-- Role: quizthing
-- DROP ROLE quizthing;

CREATE ROLE quizthing WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md57c11eaa49182b1b1942aeeeac2ce69f7';